# Generated by Django 5.1.2 on 2024-10-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito_compra',
            name='estado',
            field=models.BooleanField(choices=[(False, 'Pendiente'), (True, 'Completado')], default=False),
        ),
    ]
