# Generated by Django 5.1.2 on 2024-10-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito_compra',
            name='canitdad_producto',
            field=models.FloatField(default=0),
        ),
    ]
