# Generated by Django 5.1.2 on 2024-10-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito_compra',
            name='canitdad_producto',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='producto'),
        ),
    ]
